import Head from 'next/head'
import Cadastro from '../components/Vitrine/Cadastro'



export default function Home() {
  return (
    <div style={{height:"100vh"}}>
      <Head>
        <title>Wolff's Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lobologo.png" />
      </Head>
      
      <Cadastro/>
     
    </div>
  )
}