import Head from 'next/head'
import Login from '../components/Login'


export default function Home() {
  return (
    <div className='' style={{height:"100vh"}}>
      <Head>
        <title>Wolff's Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lobologo.png" />
      </Head>
      
      <Login/>
     
    </div>
  )
}