import Head from "next/head";
import Transferencia from '../components/Usuario/Transferencia'
import Inicio from '../components/Usuario/Inicio'

export default function Home(){
    return(
        <div>
        <Head>
        <title>Wolff's Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lobologo.png" />
      </Head>

      <Inicio/>

      <Transferencia/>

      </div>
    )
}